In [1]:
import pandas as pd

majors_df = pd.read_excel("30DayChart-5_data.xlsx", header=1)
majors_df.head()

,Field of study,1970-71,1975-76,1980-81,1985-86,1990-91,1995-96,2000-01,2005-06,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,839730.0,925746.0,935140.0,987823.0,1094538.0,1164792.0,1244171.0,1485104.0,1840381.0,1870150.0,1894969.0,1920750.0,1956114.0,1980665.0,2013086.0,2038682.0,2066463.0,2015035.0
2,Agriculture and natural resources\1\,12674.0,19402.0,21886.0,17191.0,13363.0,21757.0,23766.0,23497.0,34304.0,35953.0,37028.0,37827.0,38782.0,40334.0,41373.0,41858.0,41921.0,40675.0
3,Architecture and related services,5570.0,9146.0,9455.0,9119.0,9781.0,8352.0,8480.0,9515.0,9757.0,9149.0,9090.0,8825.0,8579.0,8464.0,8806.0,9045.0,9296.0,9462.0
4,"Area, ethnic, cultural, gender, and group studies",2579.0,3577.0,2887.0,3021.0,4776.0,5633.0,6160.0,7878.0,8850.0,8275.0,7783.0,7840.0,7720.0,7717.0,7733.0,7771.0,7390.0,6658.0

In [2]:
# Drop row 0
majors_df = majors_df.drop(0)

In [3]:
# look at unique values in field of study
majors_df['Field of study']

1                                                 Total
2                  Agriculture and natural resources\1\
3                     Architecture and related services
4     Area, ethnic, cultural, gender, and group studies
5                    Biological and biomedical sciences
6                                           Business\2\
7       Communication, journalism, and related programs
8                           Communications technologies
9     Computer and information sciences and support ...
10                                            Education
11                                          Engineering
12                          Engineering technologies\3\
13              English language and literature/letters
14          Family and consumer sciences/human sciences
15      Foreign languages, literatures, and linguistics
16              Health professions and related programs
17    Homeland security, law enforcement, and firefi...
18                        Legal professions and studies
19    Liberal arts and sciences, general studies, an...
20                                      Library science
21                           Mathematics and statistics
22           Military technologies and applied sciences
23                      Multi/interdisciplinary studies
24    Parks, recreation, leisure, fitness, and kines...
25                     Philosophy and religious studies
26           Physical sciences and science technologies
27                                 Precision production
28                                           Psychology
29            Public administration and social services
30                          Social sciences and history
31                     Theology and religious vocations
32                  Transportation and materials moving
33                           Visual and performing arts
34                             Other and not classified
35    \1\Includes Agricultural, animal, plant, veter...
36    \2\Includes Business, management, marketing, a...
37    \3\Includes Engineering technologies and engin...
38    NOTE: Data in this table represent the 50 stat...
39    SOURCE: U.S. Department of Education, National...
Name: Field of study, dtype: object

In [4]:
# Drop everything you're not interested in
majors_df = majors_df.drop([1, 4, 12, 14, 24, 27, 34, 35, 36, 37, 38, 39])

In [5]:
# Calculate the sum of all columns except field of study and make a new column
cols_to_sum = [col for col in majors_df.columns if col != "Field of study"]
majors_df["total"] = majors_df[cols_to_sum].sum(axis=1)

In [6]:
# Drop ones with low totals
majors_df = majors_df.drop([20, 22, 18, 8, 32, 31, 3, 25, 15, 23])

In [7]:
# Take another look after picking and choosing
majors_df.sort_values(by="total", ascending=True)[['Field of study', 'total']]

                                       Field of study      total
21                         Mathematics and statistics   363118.0
26         Physical sciences and science technologies   463245.0
29          Public administration and social services   468162.0
2                Agriculture and natural resources\1\   543591.0
19  Liberal arts and sciences, general studies, an...   651310.0
17  Homeland security, law enforcement, and firefi...   736629.0
13            English language and literature/letters   797441.0
9   Computer and information sciences and support ...   987318.0
7     Communication, journalism, and related programs  1234921.0
33                         Visual and performing arts  1312312.0
5                  Biological and biomedical sciences  1578013.0
11                                        Engineering  1598975.0
28                                         Psychology  1657180.0
10                                          Education  1852822.0
30                        Social sciences and history  2649160.0
16            Health professions and related programs  2862649.0
6                                         Business\2\  5520074.0

In [8]:
majors_2000 = majors_df[['Field of study', '2000-01']]
majors_2022 = majors_df[['Field of study', '2021-22']]

In [9]:
majors_2000

                                       Field of study   2000-01
2                Agriculture and natural resources\1\   23766.0
5                  Biological and biomedical sciences   60576.0
6                                         Business\2\  263515.0
7     Communication, journalism, and related programs   58013.0
9   Computer and information sciences and support ...   44142.0
10                                          Education  105458.0
11                                        Engineering   58209.0
13            English language and literature/letters   50569.0
16            Health professions and related programs   75537.0
17  Homeland security, law enforcement, and firefi...   25211.0
19  Liberal arts and sciences, general studies, an...   37962.0
21                         Mathematics and statistics   11171.0
26         Physical sciences and science technologies   18025.0
28                                         Psychology   73645.0
29          Public administration and social services   19447.0
30                        Social sciences and history  128036.0
33                         Visual and performing arts   61148.0

In [10]:
majors_2022

                                       Field of study   2021-22
2                Agriculture and natural resources\1\   40675.0
5                  Biological and biomedical sciences  131462.0
6                                         Business\2\  375418.0
7     Communication, journalism, and related programs   86043.0
9   Computer and information sciences and support ...  108503.0
10                                          Education   89410.0
11                                        Engineering  123017.0
13            English language and literature/letters   33429.0
16            Health professions and related programs  263765.0
17  Homeland security, law enforcement, and firefi...   56901.0
19  Liberal arts and sciences, general studies, an...   37887.0
21                         Mathematics and statistics   26212.0
26         Physical sciences and science technologies   28301.0
28                                         Psychology  129609.0
29          Public administration and social services   33429.0
30                        Social sciences and history  151109.0
33                         Visual and performing arts   90241.0

In [11]:
majors_2022.loc[5, 'Field of study'] = "Physical and Biological Sciences"
majors_2000.loc[5, 'Field of study'] = "Physical and Biological Sciences"

majors_2022.loc[5, '2021-22'] = majors_2022.loc[5, '2021-22'] + majors_2022.loc[26, '2021-22']
majors_2000.loc[5, '2000-01'] = majors_2000.loc[5, '2000-01'] + majors_2000.loc[26, '2000-01']

In [12]:
majors_2000 = majors_2000.drop(26)
majors_2022 = majors_2022.drop(26)

In [13]:
majors_2000['year'] = "2000"
majors_2022['year'] = "2022"

In [14]:
majors_2000

                                       Field of study   2000-01  year
2                Agriculture and natural resources\1\   23766.0  2000
5                    Physical and Biological Sciences   78601.0  2000
6                                         Business\2\  263515.0  2000
7     Communication, journalism, and related programs   58013.0  2000
9   Computer and information sciences and support ...   44142.0  2000
10                                          Education  105458.0  2000
11                                        Engineering   58209.0  2000
13            English language and literature/letters   50569.0  2000
16            Health professions and related programs   75537.0  2000
17  Homeland security, law enforcement, and firefi...   25211.0  2000
19  Liberal arts and sciences, general studies, an...   37962.0  2000
21                         Mathematics and statistics   11171.0  2000
28                                         Psychology   73645.0  2000
29          Public administration and social services   19447.0  2000
30                        Social sciences and history  128036.0  2000
33                         Visual and performing arts   61148.0  2000

In [15]:
majors_2000['2000-01'] = majors_2000['2000-01'].astype(int)
majors_2022['2021-22'] = majors_2022['2021-22'].astype(int)

In [16]:
majors_2000['Degrees'] = majors_2000.pop('2000-01')
majors_2022['Degrees'] = majors_2022.pop('2021-22')

In [17]:
majors_2000["Ranking"] = majors_2000["Degrees"].rank(ascending=False, method="first").astype(int)
majors_2022["Ranking"] = majors_2022["Degrees"].rank(ascending=False, method="first").astype(int)

# majors_2000["Ranking"] += majors_2000.groupby("year").cumcount() * 0.05
# majors_2022["Ranking"] += majors_2022.groupby("year").cumcount() * 0.05

In [18]:
final_df = pd.concat([majors_2000, majors_2022]).reset_index(drop=True)

In [19]:
final_df

                                       Field of study  year  Degrees  Ranking
0                Agriculture and natural resources\1\  2000    23766       14
1                    Physical and Biological Sciences  2000    78601        4
2                                         Business\2\  2000   263515        1
3     Communication, journalism, and related programs  2000    58013        9
4   Computer and information sciences and support ...  2000    44142       11
5                                           Education  2000   105458        3
6                                         Engineering  2000    58209        8
7             English language and literature/letters  2000    50569       10
8             Health professions and related programs  2000    75537        5
9   Homeland security, law enforcement, and firefi...  2000    25211       13
10  Liberal arts and sciences, general studies, an...  2000    37962       12
11                         Mathematics and statistics  2000    11171       16
12                                         Psychology  2000    73645        6
13          Public administration and social services  2000    19447       15
14                        Social sciences and history  2000   128036        2
15                         Visual and performing arts  2000    61148        7
16               Agriculture and natural resources\1\  2022    40675       12
17                   Physical and Biological Sciences  2022   159763        3
18                                        Business\2\  2022   375418        1
19    Communication, journalism, and related programs  2022    86043       10
20  Computer and information sciences and support ...  2022   108503        7
21                                          Education  2022    89410        9
22                                        Engineering  2022   123017        6
23            English language and literature/letters  2022    33429       14
24            Health professions and related programs  2022   263765        2
25  Homeland security, law enforcement, and firefi...  2022    56901       11
26  Liberal arts and sciences, general studies, an...  2022    37887       13
27                         Mathematics and statistics  2022    26212       16
28                                         Psychology  2022   129609        5
29          Public administration and social services  2022    33429       15
30                        Social sciences and history  2022   151109        4
31                         Visual and performing arts  2022    90241        8

In [20]:
final_df.loc[0, 'Field of study'] = "Agriculture"
final_df.loc[16, 'Field of study'] = "Agriculture"


final_df.loc[2, 'Field of study'] = "Business"
final_df.loc[18, 'Field of study'] = "Business"

final_df.loc[3, 'Field of study'] = "Communication and Journalism"
final_df.loc[19, 'Field of study'] = "Communication and Journalism"

final_df.loc[4, 'Field of study'] = "Computer and Information Sciences"
final_df.loc[20, 'Field of study'] = "Computer and Information Sciences"

final_df.loc[7, 'Field of study'] = "English Language and Literature"
final_df.loc[23, 'Field of study'] = "English Language and Literature"


final_df.loc[8, 'Field of study'] = "Health Professions"
final_df.loc[24, 'Field of study'] = "Health Professions"

final_df.loc[10, 'Field of study'] = "Liberal Arts and Sciences"
final_df.loc[26, 'Field of study'] = "Liberal Arts and Sciences"

In [21]:
final_df.to_csv('major_rankings.csv', index=False)

In [22]:
import plotly.graph_objects as go

In [23]:
def add_degree_traces(fig, df, custom_colors, year_order):
    """
    Adds traces for each district to the bump chart, including lines and annotations.
    """
    # Add a line for each district
    for i, degree in enumerate(df["Field of study"].unique()):
        degree_data = df[df["Field of study"] == degree]

        # Get the last point for the annotation
        last_point = degree_data.iloc[-1]

        # Get the index of the last year in the year_order
        last_year_index = year_order.index(last_point["year"])

        # Get the color from the custom color list (using the index 'i')
        line_color = custom_colors[i % len(custom_colors)]

        # Add the line trace
        fig.add_trace(
            go.Scatter(
                x=degree_data["year"],
                y=degree_data["Ranking"],
                mode="lines+markers",
                name=degree,
                line=dict(color=line_color),
                marker=dict(size=20),
                hovertemplate="<br><b>Year: </b>%{x}<br><b>Ranking: </b>%{y}<br><b>No.of Degrees: </b>%{customdata[0]:,.2f}<extra></extra>",  # Include 'Income' in hover
                customdata=degree_data[["Degrees"]],  # Add 'Income' to custom data for hover
            )
        )

        # Add annotation with a buffer to the left of the last year point
        buffer = 0.1  # Adjust this value to increase or decrease the buffer
        fig.add_annotation(
            x=last_year_index + buffer,  # Add buffer to the x position
            y=last_point["Ranking"],
            text=degree,
            showarrow=False,  # Remove the arrow
            font=dict(size=15, color=line_color),  # Match the color of the label with the line
            xanchor="left",  # Align text to the left of the specified x position
        )

In [24]:

def get_custom_colors(background="light"):
    """
    Returns a list of custom colors in hex format for the bump chart lines.
    Based on the background type (light or dark).
    Parameters:
        background (str): Type of background, either "light" or "dark".
    Returns:
        list: A list of custom colors for the specified background type.
    """
    # Colors for light background
    colors_for_light_bg = [
        "#4B7CCC",  # Medium Blue
        "#F2668B",  # Pink
        "#03A688",  # Medium Teal
        "#FFAE3E",  # Amber
        "#B782B8",  # Purple
        "#A67F63",  # Chestnut
        "#0E8B92",  # Deep Teal
        "#D4AC2C",  # Bronze Yellow
        "#7E9F5C",  # Forest Green
        "#F7BCA3",  # Burnt Orange
        "#E63946",  # Red
        "#7DA9A7",  # Slate Blue
        "#457B9D",  # Steel Blue
        "#E094AC",  # Rose
        "#1D3557",  # Dark Blue
        "#2A9D8F",  # Teal Green
        "#B38A44",  # Antique Gold
        "#C68045",  # Copper
        "#264653",  # Charcoal Blue
    ]

    # Colors for dark background
    colors_for_dark_bg = [
        "#A8C9F4",  # Pastel Blue
        "#FFB3C6",  # Pastel Pink
        "#A0E5D6",  # Soft Teal
        "#FFEC88",  # Pastel Yellow
        "#E2A8D3",  # Pastel Lavender
        "#D0B89D",  # Soft Tan
        "#80D0D4",  # Light Aqua
        "#F1E59B",  # Pale Lemon
        "#B4D79E",  # Light Mint Green
        "#F2B48C",  # Soft Coral
        "#FFB4B4",  # Light Red
        "#A2D1D1",  # Light Cyan
        "#7FBCD1",  # Light Steel Blue
        "#F1A8D6",  # Light Rose
        "#5C7F9E",  # Light Denim Blue
        "#70C7B7",  # Soft Green-Teal
        "#C8A67F",  # Pastel Gold
        "#D7A584",  # Light Copper
        "#A4B6D4",  # Soft Charcoal Blue
    ]

    if background == "dark":
        return colors_for_dark_bg
    else:
        return colors_for_light_bg

In [25]:
def add_subtitle(fig, subtitle, subtitle_font_size=14, subtitle_color="gray", y_offset=0.92, x_offset=0.5):
    """
    Adds a subtitle to a Plotly figure.
    """
    fig.add_annotation(
        text=subtitle,
        x=x_offset,  # Horizontal position
        y=y_offset,  # Vertical position
        xref="paper",
        yref="paper",
        showarrow=False,
        font=dict(size=subtitle_font_size, color=subtitle_color),
        align="center",
    )
    return fig

def add_footer(fig, footer, footer_font_size=12, footer_color="gray", y_offset=-0.1, x_offset=0.5):
    """
    Adds a footer to a Plotly figure.
    """
    fig.add_annotation(
        text=footer,
        x=x_offset,  # Horizontal position
        y=y_offset,  # Vertical position
        xref="paper",
        yref="paper",
        showarrow=False,
        font=dict(size=footer_font_size, color=footer_color),
        align="center",
    )
    return fig

def customize_layout(fig):
    """
    Customizes the layout of the figure, including titles, axis settings, and grid visibility.
    """
    # Invert the y-axis because higher rankings should appear at the top
    fig.update_yaxes(
        autorange="reversed",
        tickmode="linear",
        dtick=1,
        showticklabels=False  # Remove y-axis labels
    )

    # Customize layout settings (titles, grid, etc.)
    fig.update_layout(
        title={
        "text": "Ranking of Majors by Degrees awarded: 2000 vs. 2022",
        "y": 0.925,  # Adjust vertical position (default is 1.0)
    },
        plot_bgcolor='rgba(255,255,255,1)',
        paper_bgcolor='rgba(255,255,255,1)',
        font=dict(family='Poppins'),
        height=700,
        width=700,
        showlegend=False,  # Remove the legend
        xaxis_showgrid=False,  # Remove grid lines from the x-axis
        yaxis_showgrid=False,  # Remove grid lines from the y-axis
    )

In [26]:
def create_bump_chart(df):
    """
    Creates and displays the bump chart using the provided dataframe.
    """
    # Get the list of custom colors
    custom_colors = get_custom_colors()

    # Create the bump chart figure
    fig = go.Figure()

    # Add district traces to the figure
    year_order = sorted(df["year"].unique())
    add_degree_traces(fig, df, custom_colors, year_order)

    # Add a subtitle to the figure
    subtitle = "Visualizing changes in major popularity over 20 years"
    add_subtitle(fig, subtitle, subtitle_font_size=15, subtitle_color="grey", y_offset=1.050, x_offset=-0.0875)

    # Add a footer to the figure
    footer = "Source: National Center for Educational Statistics"
    add_footer(fig, footer, footer_font_size=12, footer_color="grey", y_offset=-0.1, x_offset=0.35)

    # Customize the layout of the figure
    customize_layout(fig)

    # Show the figure
    fig.show()

    return fig
# Assuming df_income is your DataFrame
fig = create_bump_chart(final_df)

In [27]:
pip install -U kaleido

Requirement already satisfied: kaleido in /Users/jkurra/opt/anaconda3/lib/python3.9/site-packages (0.2.1)
Note: you may need to restart the kernel to use updated packages.

In [28]:
fig.write_image("30DayChart-5.png")

In [29]:
# fig.write_html("30DayChart-5.html")